services:
  caddy:
    container_name: jawnix-caddy
    environment:
      JAWNIX_DOMAIN: ":8080"
    ports: !reset []
    networks:
      - private
      - edge

networks:
  edge:
    external: true
    name: buzz-prod_buzz-net
