import { Button } from "../../design-system/primitives/Button";
import { Cluster, Page, Section } from "../../design-system/primitives/layout";
import { useTheme } from "../../design-system/theme/ThemeProvider";
import type { Theme } from "../../design-system/theme/ThemeProvider";
import { useDocumentTitle } from "../shell/useDocumentTitle";
import type { GallerySection } from "./gallery/types";

const THEMES: { value: Theme; label: string }[] = [
  { value: "jawnix", label: "Jawnix" },
  { value: "opaline", label: "Opaline" },
  { value: "terminal", label: "Terminal" },
];

/*
 * Sections are discovered, not imported.
 *
 * This route is the fixture the accessibility sweep and the visual-regression
 * baseline run against, so every slice that adds a primitive has to register it
 * here. When that registration was a shared import block, two slices building in
 * parallel conflicted on it every time — observed between #48 and #55.
 *
 * Globbing removes the shared edit entirely: a slice adds one
 * `gallery/*.gallery.tsx` file and nothing else. New files never conflict.
 */
const modules = import.meta.glob<{ default: GallerySection }>("./gallery/*.gallery.tsx", {
  eager: true,
});

const SECTIONS: GallerySection[] = Object.entries(modules)
  .map(([path, module]) => {
    const section = module.default;
    if (!section?.title || typeof section.order !== "number" || !section.Component) {
      // A malformed section would otherwise vanish silently and take its
      // accessibility coverage with it.
      throw new Error(`Gallery section ${path} must default-export { title, order, Component }.`);
    }
    return section;
  })
  // Order, then title, so the sequence is stable for visual-regression diffing
  // regardless of filesystem enumeration order.
  .sort((a, b) => a.order - b.order || a.title.localeCompare(b.title));

/**
 * Gallery of every design-system primitive.
 *
 * A working fixture rather than documentation: the accessibility sweep and the
 * visual-regression baseline both run against this one route, so a primitive
 * that regresses in either theme fails a test instead of shipping.
 *
 * To add a primitive, add a file under `gallery/`. Do not edit this file.
 */
export function DesignSystemRoute() {
  useDocumentTitle("Design system");
  const { theme, setTheme } = useTheme();

  return (
    <Page
      title="Design system"
      description="Every shell primitive, in all three themes. Used as the accessibility and visual-regression fixture."
      actions={
        <Cluster gap={2}>
          {THEMES.map((option) => (
            <Button
              key={option.value}
              variant={theme === option.value ? "primary" : "secondary"}
              aria-pressed={theme === option.value}
              onClick={() => setTheme(option.value)}
            >
              {option.label}
            </Button>
          ))}
        </Cluster>
      }
    >
      {SECTIONS.map(({ title, description, Component }) => (
        <Section key={title} title={title} {...(description ? { description } : {})}>
          <Component />
        </Section>
      ))}
    </Page>
  );
}
